name: CI Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - run: dotnet restore ./University-Portal/University-Portal.sln

      - run: dotnet build ./University-Portal/University-Portal.sln -c Release --no-restore

      - run: dotnet test ./University-Portal.Tests/University-Portal.Tests.csproj -c Release --no-build